### ISSUE TITLE
Make option to simulate `widthOnly` without 'whitespace:nowrap'

### ISSUE THREAD

**Issue by alexdantas** [jquery-textfill/jquery-textfill#23]
By default `jquery-textfill` does this:
![default](https://cloud.githubusercontent.com/assets/1382398/3608558/466c9a3e-0d63-11e4-9c0c-820a6463fa3d.png)

And with `widthOnly:true` it does this:
![width-only-with-nowrap](https://cloud.githubusercontent.com/assets/1382398/3608559/493120be-0d63-11e4-87af-51ade8014c60.png)

As discussed on #21 (specifically, [here](https://github.com/jquery-textfill/jquery-textfill/pull/21#issuecomment-49255124)), there should be an option that does this:
![width-only-without-nowrap](https://cloud.githubusercontent.com/assets/1382398/3608560/4970a2fc-0d63-11e4-89ad-5b45e37e5d6e.png)

**Comment by GeekyMonkey** [comment]
Leplolt's pull request has been merged in.
