### ISSUE TITLE
Resize is not working in Safari Mac 

### ISSUE THREAD

**Issue by benoitbar** [jquery-textfill/jquery-textfill#28]
I use your lib to resize a text in my page but resize not working in Safari Mac.
When I use debug option, I can see in console font-size = undefined. You can view the bug here : http://culture-scientifique-auvergne.fr/

**Comment by kshmir** [comment]
@alexdantas I was using this plugin and attempted to load it only with zepto.js... so the ":visible:first" selector didn't work out.

So I made this change...

      var ourText = $(Opts.innerTag, this).filter(function(el) {
        return $(el).css('display') !== 'hidden';
      }).first();

I'm not sure it's good enough, it should probably check some other stuff but it worked out and helped to make zepto.js compatible :) Seems to work on Chrome Android and iOS, which was my need.

**Comment by GeekyMonkey** [comment]
That behaviour has changed due to pull requests.
