### ISSUE TITLE
h1

### ISSUE THREAD

**Issue by zarza** [jquery-textfill/jquery-textfill#35]
Hi there, and thank you for your time.

In order to affect an H1, shall I just add:
innerTag         : 'h1',

?

If so, any idea of why it is not working? and it does with span.

**Comment by AndrewHYi** [comment]
Try setting the h1's display to 'inline' (worked for me).

**Comment by GeekyMonkey** [comment]
Generally the h1 would be the outer tag, and the inner would be a span.  But anything inline should work.
