### ISSUE TITLE
Options on website outdated

### ISSUE THREAD

**Issue by CoDEmanX** [jquery-textfill/jquery-textfill#46]
Compare these two:
http://jquery-textfill.github.io/#about
https://github.com/jquery-textfill/jquery-textfill/blob/master/README.md#options

The latter lists changeLineHeight as option, whereas the former lists minFontPixels twice. The explicit\* options lack some details.

**Comment by GeekyMonkey** [comment]
Good catch. Thanks. This has been updated.
