### ISSUE TITLE
Only reduce size, but not increase

### ISSUE THREAD

**Issue by danielocdh** [jquery-textfill/jquery-textfill#49]
Is there an easy way to change the code to only reduce the size of the text and let it be if it is smaller than the container?

**Comment by kiprobinson** [comment]
+1. I'm hoping to use this to handle button labels that can get ridiculously large in German translation, but I only want the large labels to shrink--small labels should not enlarge.

**Comment by zhengs** [comment]
+1. Or, is there a way to get the final font size computed by the algorithm? If that's possible, we might be able to compare the computed size vs. original size, and decide which one to use.

**Comment by GeekyMonkey** [comment]
Just set the max font size to your default font size.  Then it will only shrink and not grow.
