### ISSUE TITLE
widthOnly bug

### ISSUE THREAD

**Issue by ishan911** [jquery-textfill/jquery-textfill#57]
if ((ourText.width()  > maxWidth) ||
				(ourText.height() > maxHeight && !Opts.widthOnly))

Should be changed to. 

if ((ourText.width()  > maxWidth) ||
				(ourText.height() > maxHeight) && !Opts.widthOnly) {

If not the widthOnly option doesnt work

**Comment by GeekyMonkey** [comment]
This was included in a pull request.
